# Generated by Django 5.1 on 2026-06-02 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisresult',
            name='matched_keywords',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='analysisresult',
            name='missing_keywords',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='analysisresult',
            name='suggestions',
            field=models.TextField(blank=True),
        ),
    ]
